controllers/QueuesController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\SleepJob;
use app\models\RandomSleepJob;
use app\components\YiiCommand;
use app\components\BackgroundProcess;
use QueueJobs\Manager;
class QueuesController extends Controller
{
    protected $qNames = ['sleep', 'randomSleep'];
    public function behaviors()
    {
        return [];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    public function actionIndex()
    {
        $m = new Manager();
        $queues = [];
        foreach ($this->qNames as $qName) {
            $pids = BackgroundProcess::findProcess("yii worker/spawn {$qName}");
            $q = [
                'name' => $qName,
                'length' => $m->qLen($qName),
                'pids' => $pids,
            ];
            $queues[] = $q;
        }
        return $this->render(
            'index',
            array(
                'queues' => $queues,
            )
        );
    }
    public function actionAjaxindex()
    {
        $m = new Manager();
        $queues = [];
        foreach ($this->qNames as $qName) {
            $pids = BackgroundProcess::findProcess("yii worker/spawn {$qName}");
            $q = [
                'name' => $qName,
                'length' => $m->qLen($qName),
                'pids' => $pids,
            ];
            $queues[] = $q;
        }
        return $this->renderAjax(
            '_queuesTable',
            array(
                'queues' => $queues,
            )
        );
    }
    public function actionAddworker($type){
        if (!in_array($type, $this->qNames)) {
            throw new yii\web\BadRequestHttpException('Unknown queue type', 400);
        }
        $command = new YiiCommand('worker', 'spawn');
        $command->arguments = [$type];
        $process = new BackgroundProcess($command->construct());
        $process->run();
    }
    public function actionKillworker($pid){
        $pids = BackgroundProcess::findProcess("yii worker/spawn");
        if (in_array($pid, $pids)) {
            BackgroundProcess::killProcess($pid);
        }
    }
}

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

/**
 * @var \yii\web\View $this
 * @var string $content
 */
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => 'Simple job queues',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    ['label' => 'Home', 'url' => ['/site/jobs']],
                    ['label' => 'Queues', 'url' => ['/queues/index']],
                ],
            ]);
            NavBar::end();
        ?>

        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="pull-left">&copy; My Company <?= date('Y') ?></p>
            <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>