controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\SleepJob;
use app\models\RandomSleepJob;
use app\components\YiiCommand;
use app\components\BackgroundProcess;
use QueueJobs\Manager;
class SiteController extends Controller
{
    public function behaviors()
    {
        return [];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionJobs()
    {
        $provider = $this->getJobsProvider();
        $page = \Yii::$app->request->getQueryParam('page', 1);
        return $this->render(
            'jobs',
            array(
                'provider' => $provider,
                'page' => $page,
            )
        );
    }
    public function actionAjaxjobs()
    {
        $provider = $this->getJobsProvider();
        $jobs = $provider->getModels();
        return $this->renderAjax('_jobsTable', [
            'jobs' => $jobs,
        ]);
    }
    public function actionDeletejob($id)
    {
        $m = new Manager();
        $jobs = $m->deleteJob($id);
        return $this->redirect(['site/jobs']);
    }
    public function actionAddsleepjob()
    {
        $m = new Manager();
        $j = new SleepJob('10');
        $m->addJob($j);
    }
    public function actionAddrandomsleepjob()
    {
        $m = new Manager();
        $j = new RandomSleepJob();
        $m->addJob($j);
    }
    private function getJobsProvider()
    {
        $m = new Manager();
        $jobs = $m->getJobs();
        $provider = new \yii\data\ArrayDataProvider([
            'key' => 'id',
            'allModels' => $jobs,
            'sort' => [
                'attributes' => ['queued'],
                'defaultOrder' => [
                    'queued' => SORT_DESC,
                ]
            ],
            'pagination' => [
                'pageSize' => 5,
            ],
        ]);
        return $provider;
    }
}

views/site/_jobsTable.php
<?php
use yii\helpers\ArrayHelper;
use yii\bootstrap\Progress;
use app\helpers\DateHelper;
use app\helpers\JobsHelper;
$this->title = 'Jobs';
$this->registerJsFile(\Yii::$app->urlManager->getHostInfo(). '/js/jobs.js', [\yii\web\JqueryAsset::className()]);
?>
<table class="table table-hover table-bordered">
    <tr>
        <th>Type</th>
        <th>Status</th>
        <th>Progress</th>
        <th>Queued</th>
        <th>Started</th>
        <th>Finished</th>
        <th>Remove</th>
    </tr>
    <?php foreach ($jobs as $job): ?>
    <tr>
        <td><?= ArrayHelper::getValue($job, 'type', ''); ?></td>
        <td><?= JobsHelper::textStatus(ArrayHelper::getValue($job, 'status', '')); ?></td>
        <td style="width: 20%"><?= Progress::widget([
            'percent' => ArrayHelper::getValue($job, 'progress', ''),
        ]); ?></td>
        <td><?= DateHelper::mysqlFormat(ArrayHelper::getValue($job, 'queued', '')); ?></td>
        <td><?= DateHelper::mysqlFormat(ArrayHelper::getValue($job, 'started', '')); ?></td>
        <td><?= DateHelper::mysqlFormat(ArrayHelper::getValue($job, 'finished', '')); ?></td>
        <td>
            <div class="btn-group">
                <a href="<?= \Yii::$app->urlManager->createUrl(['site/deletejob', 'id' => $job['id']]); ?>" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-remove"></span></a>
            </div>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

views/site/about.php
<?php
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 */
$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\captcha\Captcha;

/**
 * @var yii\web\View $this
 * @var yii\widgets\ActiveForm $form
 * @var app\models\ContactForm $model
 */
$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

    <div class="alert alert-success">
        Thank you for contacting us. We will respond to you as soon as possible.
    </div>

    <p>
        Note that if you turn on the Yii debugger, you should be able
        to view the mail message on the mail panel of the debugger.
        <?php if (Yii::$app->mail->useFileTransport): ?>
        Because the application is in development mode, the email is not sent but saved as
        a file under <code><?= Yii::getAlias(Yii::$app->mail->fileTransportPath) ?></code>.
        Please configure the <code>useFileTransport</code> property of the <code>mail</code>
        application component to be false to enable email sending.
        <?php endif; ?>
    </p>

    <?php else: ?>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var string $name
 * @var string $message
 * @var Exception $exception
 */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/**
 * @var yii\web\View $this
 */
$this->title = 'My Yii Application';
?>
<div class="site-index">
<?php var_dump($m->qLen('sleep')); ?>
</div>

views/site/jobs.php
<?php
$this->title = 'Jobs';
$host = \Yii::$app->urlManager->getHostInfo();
$this->registerJsFile($host . '/js/jobs.js', [\yii\web\JqueryAsset::className()]);
$this->registerJsFile($host . '/js/ajaxyContainer.js', [\yii\web\JqueryAsset::className()]);
$this->registerJsFile($host . '/js/ajaxyButton.js', [\yii\web\JqueryAsset::className()]);
?>
<div class="site-index">
    <div>
        <button
            href="<?= \Yii::$app->urlManager->createUrl(['site/addsleepjob']); ?>"
            class="ajaxy-button btn btn-default"
        >
            Add SleepJob
        </button>
        <button
            href="<?= \Yii::$app->urlManager->createUrl(['site/addrandomsleepjob']); ?>"
            class="ajaxy-button btn btn-default"
        >
            Add RandomSleepJob
        </button>
    </div>
    <div
        id="table-container"
        class="site-index"
        data-url="<?= \Yii::$app->urlManager->createUrl(['site/ajaxjobs', 'page' => $page]); ?>"
    >
    <?= $this->render('_jobsTable', [
        'jobs' => $provider->getModels(),
    ]);
    ?>
    </div>
    <?= \yii\widgets\LinkPager::widget([
            'pagination' => $provider->getPagination(),
        ]);
    ?>
</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var yii\widgets\ActiveForm $form
 * @var app\models\LoginForm $model
 */
$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe', [
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ])->checkbox() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>