controllers/QueuesController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\SleepJob;
use app\models\RandomSleepJob;
use app\components\YiiCommand;
use app\components\BackgroundProcess;
use QueueJobs\Manager;
class QueuesController extends Controller
{
    protected $qNames = ['sleep', 'randomSleep'];
    public function behaviors()
    {
        return [];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    public function actionIndex()
    {
        $m = new Manager();
        $queues = [];
        foreach ($this->qNames as $qName) {
            $pids = BackgroundProcess::findProcess("yii worker/spawn {$qName}");
            $q = [
                'name' => $qName,
                'length' => $m->qLen($qName),
                'pids' => $pids,
            ];
            $queues[] = $q;
        }
        return $this->render(
            'index',
            array(
                'queues' => $queues,
            )
        );
    }
    public function actionAjaxindex()
    {
        $m = new Manager();
        $queues = [];
        foreach ($this->qNames as $qName) {
            $pids = BackgroundProcess::findProcess("yii worker/spawn {$qName}");
            $q = [
                'name' => $qName,
                'length' => $m->qLen($qName),
                'pids' => $pids,
            ];
            $queues[] = $q;
        }
        return $this->renderAjax(
            '_queuesTable',
            array(
                'queues' => $queues,
            )
        );
    }
    public function actionAddworker($type){
        if (!in_array($type, $this->qNames)) {
            throw new yii\web\BadRequestHttpException('Unknown queue type', 400);
        }
        $command = new YiiCommand('worker', 'spawn');
        $command->arguments = [$type];
        $process = new BackgroundProcess($command->construct());
        $process->run();
    }
    public function actionKillworker($pid){
        $pids = BackgroundProcess::findProcess("yii worker/spawn");
        if (in_array($pid, $pids)) {
            BackgroundProcess::killProcess($pid);
        }
    }
}

views/queues/_queuesTable.php
<?php
use yii\bootstrap\Progress;
use app\helpers\MiscHelper;

foreach ($queues as $q):
?>
  <div>
    <h3><?= $q['name']; ?></h3>
    <p>Length: <?= Progress::widget([
      'percent' => MiscHelper::limitValue($q['length'], 100),
      'label' => $q['length'],
    ]); ?></p>
    <div>
      <h6 class="pull-left">Workers: <?= count($q['pids']); ?></h6>
      <button
          href="<?= \Yii::$app->urlManager->createUrl(['queues/addworker', 'type' => $q['name']]); ?>"
          class="ajaxy-button btn btn-default pull-right"
      >
          Add worker
      </button>
    </div>

    <table class="table table-hover table-bordered">
    <?php
      if ($q['pids']):
    ?>
        <tr><th>PID</th><th>Kill worker</th></tr>
    <?php
        foreach ($q['pids'] as $pid): ?>
        <tr>
          <td><?= $pid; ?></td>
          <td style="width: 10%">
            <div class="btn-group">
              <a
                href="<?= \Yii::$app->urlManager->createUrl(['queues/killworker', 'pid' => $pid]); ?>"
                class="ajaxy-button btn btn-default btn-xs">
                <span class="glyphicon glyphicon-remove"></span>
              </a>
            </div>
          </td>
        </tr>
    <?php
        endforeach;
      else:
    ?>
        <tr><td>No workers found...</td></tr>
    <?php
      endif;
    ?>
    </table>
  </div>
<?php endforeach; ?>

views/queues/index.php
<?php
use yii\bootstrap\Progress;
use app\helpers\MiscHelper;

$this->title = 'Queues';
$host = \Yii::$app->urlManager->getHostInfo();
$this->registerJsFile($host . '/js/ajaxyContainer.js', [\yii\web\JqueryAsset::className()]);
$this->registerJsFile($host . '/js/ajaxyButton.js', [\yii\web\JqueryAsset::className()]);
// $this->registerJsFile($host . '/js/queues.js', [\yii\web\JqueryAsset::className()]);
?>
<div class="queues-index">
  <div
      id="table-container"
      class="site-index"
      data-url="<?= \Yii::$app->urlManager->createUrl(['queues/ajaxindex']); ?>"
  >
  <?= $this->render('_queuesTable', [
      'queues' => $queues,
  ]);
  ?>
  </div>
</div>